# Generated by Django 5.1.4 on 2025-02-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('analise', 'Em Análise'), ('rejeitado', 'Rejeitado'), ('devolvido', 'Devolvido'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
