# Generated by Django 5.1.6 on 2025-03-04 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolos", "0002_protocolo_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolo",
            name="cnpj",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name="protocolo",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="protocolo",
            name="data",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="protocolo",
            name="data_hora_lancamento",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="protocolo",
            name="data_nota_fiscal",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="protocolo",
            name="descontos_irrf",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="protocolo",
            name="descontos_iss",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="protocolo",
            name="descricao_servicos",
            field=models.TextField(default="Descrição padrão"),
        ),
        migrations.AddField(
            model_name="protocolo",
            name="endereco",
            field=models.CharField(default="Endereço padrão", max_length=255),
        ),
        migrations.AddField(
            model_name="protocolo",
            name="nome",
            field=models.CharField(default="Nome padrão", max_length=255),
        ),
        migrations.AddField(
            model_name="protocolo",
            name="nome_empresa",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="protocolo",
            name="tipo_pf",
            field=models.CharField(
                blank=True,
                choices=[("RECIBO", "Recibo"), ("NOTA_FISCAL", "Nota Fiscal")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="protocolo",
            name="valor_bruto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="protocolo",
            name="valor_liquido",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="numero",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="status",
            field=models.CharField(
                choices=[
                    ("pago", "Pago"),
                    ("analise", "Em Análise"),
                    ("rejeitado", "Rejeitado"),
                    ("pendente", "Pendente"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocolos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
