# Generated by Django 5.1.6 on 2025-02-26 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolos", "0002_protocolo_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolo",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="numero",
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="status",
            field=models.CharField(
                choices=[
                    ("pago", "Pago"),
                    ("analise", "Em Análise"),
                    ("rejeitado", "Rejeitado"),
                    ("pendente", "Pendente"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocolos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
