# Generated by Django 5.1.6 on 2025-03-04 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolos", "0003_protocolo_cnpj_protocolo_cpf_protocolo_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolo",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocolos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
