# Generated by Django 5.1.6 on 2025-03-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolos", "0004_alter_protocolo_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolo",
            name="numero_nota_fiscal",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
