# Generated by Django 5.1.6 on 2025-03-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolos", "0006_protocolo_numero_recibo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolo",
            name="numero_recibo",
            field=models.CharField(
                default="a6cd955abf3a4cd88e133ac1b3365a09",
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]
