# Generated by Django 5.1.6 on 2025-03-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolos", "0007_alter_protocolo_numero_recibo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolo",
            name="numero_recibo",
            field=models.CharField(
                default="25105c04b63148f889b473de03c8d6c2",
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]
