# Generated by Django 5.1.6 on 2025-03-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolos", "0008_alter_protocolo_numero_recibo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protocolo",
            name="numero",
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="numero_recibo",
            field=models.CharField(
                default="900b70ee3a3e4956952a749b5ef7417f",
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]
