# Generated by Django 5.1.6 on 2025-03-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolos", "0009_remove_protocolo_numero_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolo",
            name="numero",
            field=models.CharField(
                default=0, editable=False, max_length=20, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="numero_recibo",
            field=models.CharField(
                default="e013644ace0d40ffbe16ed9d8c062711",
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]
