# Generated by Django 5.1.6 on 2025-03-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolos", "0010_protocolo_numero_alter_protocolo_numero_recibo"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolo",
            name="descontar_iss",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="protocolo",
            name="tipo_nf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NFe", "Nota Fiscal Eletrônica (NFe)"),
                    ("NFSe", "Nota Fiscal de Serviços Eletrônica (NFSe)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="numero_recibo",
            field=models.CharField(
                default="4ba71256a81e4babaea5badec402629c",
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]
