# Generated by Django 5.1.6 on 2025-03-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolos", "0011_protocolo_descontar_iss_protocolo_tipo_nf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolo",
            name="simples_nacional",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="numero_recibo",
            field=models.CharField(
                default="6018c99a57124b39a8141e6f94ab1e4d",
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]
