# Generated by Django 5.1.6 on 2025-03-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolos", "0012_protocolo_simples_nacional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolo",
            name="descricao",
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="descricao_servicos",
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="numero_recibo",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
