# Generated by Django 5.1.6 on 2025-03-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolos", "0013_alter_protocolo_descricao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolo",
            name="tipo_nf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NFe", "Nota Fiscal (NFe)"),
                    ("NFSe", "Nota Fiscal de Serviços (NFSe)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
