# Generated by Django 5.1.6 on 2025-03-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolos", "0014_alter_protocolo_tipo_nf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolo",
            name="cnpj",
            field=models.CharField(blank=True, default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="nome_empresa",
            field=models.CharField(blank=True, default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="numero_nota_fiscal",
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="tipo_nf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NFe", "Nota Fiscal (NFe)"),
                    ("NFSe", "Nota Fiscal de Serviços (NFSe)"),
                ],
                default=0,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="tipo_pf",
            field=models.CharField(
                blank=True,
                choices=[("RECIBO", "Recibo"), ("NOTA_FISCAL", "Nota Fiscal")],
                default=0,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
