# Generated by Django 5.1.6 on 2025-03-13 14:09

import protocolos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolos", "0016_alter_protocolo_descontos_irrf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocoloanexo",
            name="arquivo",
            field=models.FileField(
                upload_to=protocolos.models.protocolo_anexo_upload_to
            ),
        ),
    ]
