# Generated by Django 5.1.4 on 2025-01-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='Usuário Master', max_length=100),
            preserve_default=False,
        ),
    ]
