# Generated by Django 5.1.4 on 2025-02-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='tipo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PJ', 'Pessoa Jurídica'), ('PF', 'Pessoa Física')], max_length=2, null=True),
        ),
    ]
