# Generated by Django 5.1.6 on 2025-02-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_remove_perfil_tipo_usuario_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_master",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.CharField(max_length=255),
        ),
    ]
