# Generated by Django 5.1.6 on 2025-03-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_alter_usuario_is_approved_alter_usuario_is_master_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Aprovado?"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_master",
            field=models.BooleanField(default=False, verbose_name="É Master?"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
