# Generated by Django 5.1.6 on 2025-03-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0007_alter_usuario_is_approved_alter_usuario_is_master_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="cnpj",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="numero",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
