# Generated by Django 5.1.6 on 2025-03-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0008_perfil_cpf_alter_perfil_cnpj_alter_perfil_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[("PJ", "Pessoa Jurídica"), ("SP", "Servidor Público")],
                max_length=2,
                null=True,
            ),
        ),
    ]
